add_custom_command( TARGET SnaxClang POST_BUILD COMMAND mkdir -p ${CMAKE_BINARY_DIR}/bin )
macro( snax_clang_install file )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/snax_llvm/bin)
   add_custom_command( TARGET SnaxClang POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( snax_clang_install )

macro( snax_clang_install_and_symlink file symlink )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/snax_llvm/bin)
   add_custom_command( TARGET SnaxClang POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   add_custom_command( TARGET SnaxClang POST_BUILD COMMAND cd ${CMAKE_BINARY_DIR}/bin && ln -sf ${file} ${symlink} )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( snax_clang_install_and_symlink )

macro( snax_tool_install file )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/tools/bin)
   add_custom_command( TARGET SnaxTools POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( snax_tool_install )

macro( snax_tool_install_and_symlink file symlink )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/tools/bin)
   add_custom_command( TARGET SnaxTools POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   add_custom_command( TARGET SnaxTools POST_BUILD COMMAND cd ${CMAKE_BINARY_DIR}/bin && ln -sf ${file} ${symlink} )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( snax_tool_install_and_symlink )

macro( snax_libraries_install)
   execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/lib)
   execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/include)
   install(DIRECTORY ${CMAKE_BINARY_DIR}/lib/ DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
   install(DIRECTORY ${CMAKE_BINARY_DIR}/include/ DESTINATION ${CMAKE_INSTALL_FULL_INCLUDEDIR})
endmacro( snax_libraries_install )

snax_clang_install_and_symlink(llvm-ranlib snax-ranlib)
snax_clang_install_and_symlink(llvm-ar snax-ar)
snax_clang_install_and_symlink(llvm-nm snax-nm)
snax_clang_install_and_symlink(llvm-objcopy snax-objcopy)
snax_clang_install_and_symlink(llvm-objdump snax-objdump)
snax_clang_install_and_symlink(llvm-readobj snax-readobj)
snax_clang_install_and_symlink(llvm-readelf snax-readelf)
snax_clang_install_and_symlink(llvm-strip snax-strip)
snax_clang_install(opt)
snax_clang_install(llc)
snax_clang_install(lld)
snax_clang_install(ld.lld)
snax_clang_install(ld64.lld)
snax_clang_install(clang-7)
snax_clang_install(wasm-ld)
snax_tool_install(snax-pp)
snax_tool_install(snax-wast2wasm)
snax_tool_install(snax-wasm2wast)
snax_tool_install(snax-cc)
snax_tool_install(snax-cpp)
snax_tool_install(snax-ld)
snax_tool_install(snax-abigen)
snax_tool_install(snax-abidiff)
snax_tool_install(snax-init)
snax_clang_install(../lib/LLVMSnaxApply${CMAKE_SHARED_LIBRARY_SUFFIX})
snax_clang_install(../lib/LLVMSnaxSoftfloat${CMAKE_SHARED_LIBRARY_SUFFIX})
snax_clang_install(../lib/snax_plugin${CMAKE_SHARED_LIBRARY_SUFFIX})
snax_libraries_install()
